use TravelAgency;

create table PlaceToVisit (
	ID INT primary key IDENTITY(1,1),
	NamePlace VARCHAR(50),
	ImagePlace VARCHAR(50)
);

SET IDENTITY_INSERT PlaceToVisit ON;

insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (1, 'Lawn', 'Vestibulum.mov');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (2, 'Lunder', 'AcTellusSemper.jpeg');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (3, 'Bashford', 'NibhQuisqueId.ppt');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (4, 'Oneill', 'Fermentum.avi');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (5, 'Jenna', 'Ipsum.avi');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (6, 'Jana', 'SuspendisseOrnareConsequat.mp3');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (7, 'Morningstar', 'Posuere.mp3');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (8, 'Fulton', 'QuamPedeLobortis.pdf');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (9, 'Village Green', 'PotentiNullamPorttitor.avi');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (10, 'Porter', 'Tincidunt.xls');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (11, 'Prentice', 'CommodoVulputateJusto.avi');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (12, 'Bartelt', 'VelitDonec.xls');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (13, 'Victoria', 'FelisEuSapien.xls');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (14, 'Magdeline', 'IntegerAcNeque.txt');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (15, 'Morrow', 'EtEros.avi');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (16, 'Commercial', 'At.avi');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (17, 'Oriole', 'InLiberoUt.ppt');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (18, 'Moose', 'JustoAliquamQuis.mp3');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (19, 'Ilene', 'MaurisEget.doc');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (20, 'Melvin', 'Urna.doc');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (21, 'Pierstorff', 'AliquetMaecenasLeo.ppt');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (22, 'Kim', 'NisiVolutpat.xls');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (23, 'Banding', 'NonLectus.mpeg');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (24, 'Farmco', 'CumSociis.png');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (25, 'Ohio', 'OrciLuctusEt.avi');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (26, 'Redwing', 'Lectus.mp3');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (27, 'Sunnyside', 'Interdum.avi');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (28, 'Carberry', 'PrimisInFaucibus.mp3');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (29, 'Utah', 'AtVulputateVitae.xls');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (30, 'Jay', 'OrciMauris.mp3');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (31, 'Golf Course', 'NequeSapien.avi');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (32, 'Mallard', 'Nec.pdf');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (33, 'Summer Ridge', 'VolutpatSapien.avi');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (34, 'Dapin', 'Ligula.tiff');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (35, 'Ramsey', 'LeoMaecenasPulvinar.avi');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (36, 'Butternut', 'Congue.mp3');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (37, 'Sullivan', 'Ipsum.ppt');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (38, 'Myrtle', 'PorttitorLacusAt.ppt');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (39, 'Monterey', 'InSagittis.doc');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (40, 'Bay', 'RisusDapibus.pdf');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (41, 'Red Cloud', 'Mauris.txt');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (42, 'Sherman', 'InHac.mp3');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (43, 'Declaration', 'Sociis.avi');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (44, 'Shopko', 'Maecenas.txt');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (45, 'Fair Oaks', 'BlanditNon.png');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (46, 'Darwin', 'Mauris.pdf');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (47, 'Roxbury', 'PenatibusEtMagnis.xls');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (48, 'Continental', 'TinciduntAnte.mp3');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (49, 'Debs', 'Vitae.avi');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (50, 'Holy Cross', 'AcConsequat.mp3');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (51, 'Lighthouse Bay', 'Elementum.avi');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (52, 'Warrior', 'Ullamcorper.ppt');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (53, 'Bashford', 'Curabitur.mpeg');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (54, 'Dapin', 'TempusVel.tiff');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (55, 'Ramsey', 'AnteVestibulumAnte.xls');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (56, 'Springs', 'Curae.jpeg');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (57, 'Schiller', 'InLacus.mov');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (58, 'New Castle', 'Dapibus.avi');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (59, 'New Castle', 'LectusIn.mp3');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (60, 'Jenifer', 'NullaNisl.mp3');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (61, 'Stuart', 'Nulla.xls');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (62, 'Macpherson', 'SapienCursus.doc');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (63, 'Bunting', 'SedInterdumVenenatis.tiff');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (64, 'Marquette', 'RhoncusSedVestibulum.avi');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (65, 'Hollow Ridge', 'Mi.xls');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (66, 'Hanson', 'DapibusDuisAt.gif');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (67, 'Vidon', 'Lobortis.png');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (68, 'Prairie Rose', 'OrciLuctus.xls');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (69, 'Kingsford', 'Felis.xls');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (70, 'Melby', 'Ultrices.mp3');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (71, 'Merry', 'PlateaDictumst.mov');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (72, 'Golden Leaf', 'EuSapien.avi');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (73, 'Logan', 'NullaDapibus.avi');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (74, 'Eastwood', 'EtCommodo.jpeg');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (75, 'Forest', 'Nonummy.xls');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (76, 'Mosinee', 'TurpisAdipiscingLorem.txt');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (77, 'Prairie Rose', 'NullamVarius.mp3');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (78, 'Schurz', 'Aliquet.jpeg');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (79, 'Vermont', 'DonecUt.doc');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (80, 'Transport', 'InLectusPellentesque.xls');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (81, 'Bunker Hill', 'AliquetMassa.xls');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (82, 'Prairieview', 'MorbiNon.mp3');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (83, 'Waxwing', 'DiamNamTristique.ppt');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (84, 'Graceland', 'DuiVel.xls');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (85, 'Jana', 'AmetTurpis.xls');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (86, 'Pond', 'Pede.xls');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (87, 'Pennsylvania', 'AliquamSit.mpeg');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (88, 'Forest', 'InTempus.mp3');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (89, 'Veith', 'UtNuncVestibulum.ppt');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (90, 'Memorial', 'Luctus.mov');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (91, 'Summerview', 'SemperRutrumNulla.avi');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (92, 'Caliangt', 'PlateaDictumst.ppt');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (93, 'Hovde', 'RisusDapibus.tiff');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (94, 'Calypso', 'JustoEtiamPretium.mp3');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (95, 'Dixon', 'PharetraMagna.xls');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (96, 'West', 'EtMagnisDis.tiff');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (97, 'Prentice', 'Pretium.xls');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (98, 'Crowley', 'Sagittis.jpeg');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (99, 'Bowman', 'EuFelisFusce.avi');
insert into PlaceToVisit (ID, NamePlace, ImagePlace) values (100, '2nd', 'Et.mp3');

SET IDENTITY_INSERT PlaceToVisit OFF;
